import { ComponentDefinition } from '../types';

export const buildingBlocks: Record<string, ComponentDefinition> = {
    'flex-block': {
        type: 'flex-block',
        category: 'building-block',
        label: 'Flex Block',
        icon: '📦',
        acceptsChildren: true,
        defaultProps: {
            direction: 'column',
            wrap: 'nowrap',
            align: 'center',
            justify: 'start',
            gap: 4,
            height: 'auto',
            padding: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            margin: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
        },
        propSchema: [
            {
                key: 'direction',
                label: 'Direction',
                type: 'select',
                options: ['row', 'column'],
                defaultValue: 'column',
            },
            {
                key: 'wrap',
                label: 'Wrap',
                type: 'select',
                options: ['nowrap', 'wrap', 'wrap-reverse'],
                defaultValue: 'nowrap',
            },
            {
                key: 'align',
                label: 'Align',
                type: 'select',
                options: ['start', 'center', 'end'],
                defaultValue: 'center',
            },
            {
                key: 'justify',
                label: 'Justify',
                type: 'select',
                options: ['start', 'center', 'end', 'between'],
                defaultValue: 'start',
            },
            {
                key: 'gap',
                label: 'Gap',
                type: 'number',
                defaultValue: 4,
            },
            {
                key: 'padding',
                label: 'Padding',
                type: 'spacing',
                defaultValue: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            },
            {
                key: 'margin',
                label: 'Margin',
                type: 'spacing',
                defaultValue: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            },
            {
                key: 'height',
                label: 'Height (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
        ],
    },

    'grid-block': {
        type: 'grid-block',
        category: 'building-block',
        label: 'Grid Block',
        icon: '⊞',
        acceptsChildren: true,
        defaultProps: {
            columns: 2,
            gap: 4,
            height: 'auto',
            padding: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            margin: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
        },
        propSchema: [
            {
                key: 'columns',
                label: 'Columns',
                type: 'select',
                options: ['1', '2', '3', '4'],
                defaultValue: 2,
            },
            {
                key: 'gap',
                label: 'Gap',
                type: 'number',
                defaultValue: 4,
            },
            {
                key: 'padding',
                label: 'Padding',
                type: 'spacing',
                defaultValue: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            },
            {
                key: 'margin',
                label: 'Margin',
                type: 'spacing',
                defaultValue: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            },
            {
                key: 'height',
                label: 'Height (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
        ],
    },

    'card-block': {
        type: 'card-block',
        category: 'building-block',
        label: 'Card',
        icon: '🎴',
        acceptsChildren: true,
        defaultProps: {
            padding: { all: '16px', top: '16px', right: '16px', bottom: '16px', left: '16px' },
            margin: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            borderRadius: 2,
            backgroundColor: '#ffffff',
            borderColor: '#e5e7eb',
            borderWidth: 1,
            shadow: 'md',
            width: 'auto',
            height: 'auto',
            direction: 'column',
            wrap: 'nowrap',
            gap: 4,
            justify: 'start',
            align: 'start',
        },
        propSchema: [
            {
                key: 'direction',
                label: 'Direction',
                type: 'select',
                options: ['row', 'column'],
                defaultValue: 'column',
            },
            {
                key: 'wrap',
                label: 'Wrap',
                type: 'select',
                options: ['nowrap', 'wrap', 'wrap-reverse'],
                defaultValue: 'nowrap',
            },
            {
                key: 'gap',
                label: 'Gap',
                type: 'number',
                defaultValue: 4,
            },
            {
                key: 'padding',
                label: 'Padding',
                type: 'spacing',
                defaultValue: { all: '16px', top: '16px', right: '16px', bottom: '16px', left: '16px' },
            },
            {
                key: 'margin',
                label: 'Margin',
                type: 'spacing',
                defaultValue: { all: '0px', top: '0px', right: '0px', bottom: '0px', left: '0px' },
            },
            {
                key: 'borderRadius',
                label: 'Border Radius',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 2,
            },
            {
                key: 'backgroundColor',
                label: 'Background Color',
                type: 'color',
                defaultValue: '#ffffff',
            },
            {
                key: 'borderColor',
                label: 'Border Color',
                type: 'color',
                defaultValue: '#e5e7eb',
            },
            {
                key: 'borderWidth',
                label: 'Border Width',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 1,
            },
            {
                key: 'shadow',
                label: 'Shadow',
                type: 'select',
                options: ['none', 'sm', 'md', 'lg'],
                defaultValue: 'md',
            },
            {
                key: 'justify',
                label: 'Justify Content',
                type: 'select',
                options: ['start', 'center', 'end', 'between'],
                defaultValue: 'start',
            },
            {
                key: 'align',
                label: 'Align Items',
                type: 'select',
                options: ['start', 'center', 'end'],
                defaultValue: 'start',
            },
            {
                key: 'width',
                label: 'Width (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'height',
                label: 'Height (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
        ],
    },
};
