import { ComponentDefinition } from '../types';

export const contentComponents: Record<string, ComponentDefinition> = {
    'button': {
        type: 'button',
        category: 'content',
        label: 'Button',
        icon: '🔘',
        acceptsChildren: false,
        defaultProps: {
            text: 'Click me',
            variant: 'default',
            size: 'default',
            width: 'auto',
            height: 'auto',
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'text',
                label: 'Text',
                type: 'text',
                defaultValue: 'Click me',
            },
            {
                key: 'variant',
                label: 'Variant',
                type: 'select',
                options: ['default', 'destructive', 'outline', 'secondary', 'ghost', 'link'],
                defaultValue: 'default',
            },
            {
                key: 'size',
                label: 'Size',
                type: 'select',
                options: ['default', 'sm', 'lg', 'icon'],
                defaultValue: 'default',
            },
            {
                key: 'width',
                label: 'Width (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'height',
                label: 'Height (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'text': {
        type: 'text',
        category: 'content',
        label: 'Text',
        icon: '📝',
        acceptsChildren: false,
        defaultProps: {
            content: 'Your text here',
            tag: 'p',
            align: 'left',
            width: 'auto',
            color: '#000000',
            fontSize: 16,
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'content',
                label: 'Content',
                type: 'text',
                defaultValue: 'Your text here',
            },
            {
                key: 'tag',
                label: 'Tag',
                type: 'select',
                options: ['p', 'h1', 'h2', 'h3', 'h4'],
                defaultValue: 'p',
            },
            {
                key: 'align',
                label: 'Align',
                type: 'select',
                options: ['left', 'center', 'right'],
                defaultValue: 'left',
            },
            {
                key: 'width',
                label: 'Width (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'color',
                label: 'Text Color',
                type: 'color',
                defaultValue: '#000000',
            },
            {
                key: 'fontSize',
                label: 'Font Size (px)',
                type: 'number',
                defaultValue: 16,
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'image': {
        type: 'image',
        category: 'content',
        label: 'Image',
        icon: '🖼️',
        acceptsChildren: false,
        defaultProps: {
            src: 'https://via.placeholder.com/300x200',
            alt: 'Placeholder image',
            width: 300,
            height: 200,
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'src',
                label: 'Image URL',
                type: 'text',
                defaultValue: 'https://via.placeholder.com/300x200',
            },
            {
                key: 'alt',
                label: 'Alt Text',
                type: 'text',
                defaultValue: 'Placeholder image',
            },
            {
                key: 'width',
                label: 'Width',
                type: 'number',
                defaultValue: 300,
            },
            {
                key: 'height',
                label: 'Height',
                type: 'number',
                defaultValue: 200,
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'input': {
        type: 'input',
        category: 'content',
        label: 'Input',
        icon: '📥',
        acceptsChildren: false,
        defaultProps: {
            placeholder: 'Enter text...',
            inputType: 'text',
            width: 'auto',
            height: 'auto',
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'placeholder',
                label: 'Placeholder',
                type: 'text',
                defaultValue: 'Enter text...',
            },
            {
                key: 'inputType',
                label: 'Type',
                type: 'select',
                options: ['text', 'email', 'password', 'number'],
                defaultValue: 'text',
            },
            {
                key: 'width',
                label: 'Width (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'height',
                label: 'Height (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'textarea': {
        type: 'textarea',
        category: 'content',
        label: 'Text Area',
        icon: '📄',
        acceptsChildren: false,
        defaultProps: {
            placeholder: 'Enter text...',
            rows: 4,
            width: 'auto',
            height: 'auto',
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'placeholder',
                label: 'Placeholder',
                type: 'text',
                defaultValue: 'Enter text...',
            },
            {
                key: 'rows',
                label: 'Rows',
                type: 'number',
                defaultValue: 4,
            },
            {
                key: 'width',
                label: 'Width (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'height',
                label: 'Height (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },
    'heading': {
        type: 'heading',
        category: 'content',
        label: 'Heading',
        icon: 'H',
        acceptsChildren: false,
        defaultProps: {
            text: 'Heading',
            level: 'h2',
            align: 'left',
            color: '#000000',
            width: 'auto',
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'text',
                label: 'Text',
                type: 'text',
                defaultValue: 'Heading',
            },
            {
                key: 'level',
                label: 'Level',
                type: 'select',
                options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
                defaultValue: 'h2',
            },
            {
                key: 'align',
                label: 'Align',
                type: 'select',
                options: ['left', 'center', 'right'],
                defaultValue: 'left',
            },
            {
                key: 'color',
                label: 'Color',
                type: 'color',
                defaultValue: '#000000',
            },
            {
                key: 'width',
                label: 'Width (px or auto)',
                type: 'text',
                defaultValue: 'auto',
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'video': {
        type: 'video',
        category: 'content',
        label: 'Video',
        icon: '🎥',
        acceptsChildren: false,
        defaultProps: {
            url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            width: 300,
            height: 200,
            controls: true,
            autoplay: false,
            marginTop: 0,
            marginBottom: 0,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'url',
                label: 'Video URL',
                type: 'text',
                defaultValue: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            },
            {
                key: 'width',
                label: 'Width',
                type: 'number',
                defaultValue: 300,
            },
            {
                key: 'height',
                label: 'Height',
                type: 'number',
                defaultValue: 200,
            },
            {
                key: 'controls',
                label: 'Show Controls',
                type: 'toggle',
                defaultValue: true,
            },
            {
                key: 'autoplay',
                label: 'Autoplay',
                type: 'toggle',
                defaultValue: false,
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'divider': {
        type: 'divider',
        category: 'content',
        label: 'Divider',
        icon: '➖',
        acceptsChildren: false,
        defaultProps: {
            color: '#e5e7eb',
            thickness: 1,
            width: '100%',
            marginTop: 2,
            marginBottom: 2,
            paddingTop: 0,
            paddingBottom: 0,
        },
        propSchema: [
            {
                key: 'color',
                label: 'Color',
                type: 'color',
                defaultValue: '#e5e7eb',
            },
            {
                key: 'thickness',
                label: 'Thickness (px)',
                type: 'number',
                defaultValue: 1,
            },
            {
                key: 'width',
                label: 'Width (e.g. 100%, 50px)',
                type: 'text',
                defaultValue: '100%',
            },
            {
                key: 'marginTop',
                label: 'Margin Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 2,
            },
            {
                key: 'marginBottom',
                label: 'Margin Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 2,
            },
            {
                key: 'paddingTop',
                label: 'Padding Top',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
            {
                key: 'paddingBottom',
                label: 'Padding Bottom',
                type: 'select',
                options: ['0', '1', '2', '3', '4'],
                defaultValue: 0,
            },
        ],
    },

    'spacer': {
        type: 'spacer',
        category: 'content',
        label: 'Spacer',
        icon: '↕️',
        acceptsChildren: false,
        defaultProps: {
            height: 32,
        },
        propSchema: [
            {
                key: 'height',
                label: 'Height (px)',
                type: 'number',
                defaultValue: 32,
            },
        ],
    },
};
